name: action-test2

on:
  workflow_dispatch:
    inputs:
      some_input:
        description: 'An example input'
      distinct_id:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo distinct ID ${{ github.event.inputs.distinct_id }}
        run: echo ${{ github.event.inputs.distinct_id }}
      - name: Print Input Value
        run: |
          echo "The value of 'some_input' is: ${{ github.event.inputs.some_input }}"

  test2:
    runs-on: ubuntu-latest
    steps:
      - name: Adding markdown
        run: |
          sleep 30
          echo "https://github.com/JanLipovsek/action_master/actions/runs/${{ github.event.inputs.some_input }}" >> $GITHUB_STEP_SUMMARY
          sleep 30